package com.tv.uscreen.yojmatv.activities.purchase.ui;

public enum VodOfferType {
    PERPETUAL,RENTAL,RENTAL_48_HRS,RENTAL_72_HRS,RENTAL_7_DAYS,RENTAL_30_DAYS,RENTAL_90_DAYS,WEEKLY,MONTHLY,QUARTERLY,RECURRING_SUBSCRIPTION,HALF_YEARLY,ANNUAL,ONE_TIME,DAYS,WEEKS,MONTHS,YEARS,
}
